// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForFile() {
  return window['go']['main']['App']['CheckForFile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadLastContent() {
  return window['go']['main']['App']['LoadLastContent']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveCurrentContent() {
  return window['go']['main']['App']['SaveCurrentContent']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveLastContent(arg1) {
  return window['go']['main']['App']['SaveLastContent'](arg1);
}

export function SetCurrentContent(arg1) {
  return window['go']['main']['App']['SetCurrentContent'](arg1);
}
