// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForFile():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadLastContent():Promise<string>;

export function OpenFile():Promise<string>;

export function SaveCurrentContent():Promise<void>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveLastContent(arg1:string):Promise<void>;

export function SetCurrentContent(arg1:string):Promise<void>;
